seed: 0
eval_iters: 1000


defaults:
  - _self_
  - model: sac
  - train: sac
  - env: grid

hydra:
  run:
    dir: results_eval/${env.name}_${env.obs_type}/n${env.num_agents}_level${env.level}/${model.name}_${now:%Y-%m-%d_%H-%M-%S}