env_name: "pick_and_delivery"
name: 'continous'
is_discrete: False
is_diff_drive: False
num_agents: 2
num_items: 10
map_size: 128
max_vel: 0.05
min_vel: 0.0
max_ang_vel: 0.25
min_ang_vel: -0.25
max_acc: 0.025
max_ang_acc: 0.125
max_life: 15
fov_r: 0.15
comm_r: 0.15
num_scans: 64
scan_range: 0.15
use_intentions: True
use_hold_item_info: True
level: 5
timeout: 100
rad: 0.02
goal_rad: 0.02
is_crashable: False
is_biased_sample: False
is_respawn: False
# reward
goal_reward: 1
dist_reward: 0
crash_penalty: -0.5
dont_hold_item_penalty: 0
time_penalty: 0
pickup_reward: 0
life_penalty: -0.0
is_decay_reward: False
decay_start: 50
decay_end: 75
min_reward: 0.1
# obstacles
obs_type: "random"
sample_type: "uniform"
obs_size_lower_bound: 0.05
obs_size_upper_bound: 0.08